/**
 * Browser-default CSS property values.
 *
 * Generated from Chrome's initial computed style on a blank document.
 * Used by the style diff engine to exclude properties that match the
 * default — only non-default values are included in the capture output.
 *
 * To regenerate, open a blank page and run:
 *   JSON.stringify(Object.fromEntries(
 *     Array.from(getComputedStyle(document.createElement('div')))
 *       .map(p => [p, getComputedStyle(document.createElement('div')).getPropertyValue(p)])
 *   ))
 * then filter to the tracked subset.
 */

export const BASELINE_STYLES: Record<string, string> = {
  alignContent: "normal",
  alignItems: "normal",
  alignSelf: "auto",
  aspectRatio: "auto",
  backdropFilter: "none",
  backgroundAttachment: "scroll",
  backgroundBlendMode: "normal",
  backgroundClip: "border-box",
  backgroundColor: "rgba(0, 0, 0, 0)",
  backgroundImage: "none",
  backgroundOrigin: "padding-box",
  backgroundPositionX: "0%",
  backgroundPositionY: "0%",
  backgroundRepeat: "repeat",
  backgroundSize: "auto",
  borderBottomColor: "rgb(0, 0, 0)",
  borderBottomLeftRadius: "0px",
  borderBottomRightRadius: "0px",
  borderBottomStyle: "none",
  borderBottomWidth: "0px",
  borderCollapse: "separate",
  borderImageOutset: "0",
  borderImageRepeat: "stretch",
  borderImageSlice: "100%",
  borderImageSource: "none",
  borderImageWidth: "1",
  borderLeftColor: "rgb(0, 0, 0)",
  borderLeftStyle: "none",
  borderLeftWidth: "0px",
  borderRightColor: "rgb(0, 0, 0)",
  borderRightStyle: "none",
  borderRightWidth: "0px",
  borderSpacing: "0px",
  borderTopColor: "rgb(0, 0, 0)",
  borderTopLeftRadius: "0px",
  borderTopRightRadius: "0px",
  borderTopStyle: "none",
  borderTopWidth: "0px",
  bottom: "auto",
  boxShadow: "none",
  boxSizing: "content-box",
  clip: "auto",
  clipPath: "none",
  clipRule: "nonzero",
  color: "rgb(0, 0, 0)",
  colorScheme: "normal",
  columnCount: "auto",
  columnFill: "balance",
  columnGap: "normal",
  columnRuleColor: "rgb(0, 0, 0)",
  columnRuleStyle: "none",
  columnRuleWidth: "0px",
  columnSpan: "none",
  columnWidth: "auto",
  contain: "none",
  containerType: "normal",
  content: "normal",
  contentVisibility: "visible",
  display: "",
  filter: "none",
  flexBasis: "auto",
  flexDirection: "row",
  flexGrow: "0",
  flexShrink: "1",
  flexWrap: "nowrap",
  fontFamily: "Times",
  fontFeatureSettings: "normal",
  fontKerning: "auto",
  fontOpticalSizing: "auto",
  fontPalette: "normal",
  fontSize: "16px",
  fontSizeAdjust: "none",
  fontStretch: "100%",
  fontStyle: "normal",
  fontWeight: "400",
  gap: "normal",
  gridAutoColumns: "auto",
  gridAutoFlow: "row",
  gridAutoRows: "auto",
  gridColumnEnd: "auto",
  gridColumnStart: "auto",
  gridRowEnd: "auto",
  gridRowStart: "auto",
  gridTemplateAreas: "none",
  gridTemplateColumns: "none",
  gridTemplateRows: "none",
  height: "auto",
  isolation: "auto",
  justifyItems: "normal",
  justifySelf: "auto",
  justifyContent: "normal",
  left: "auto",
  letterSpacing: "normal",
  lineBreak: "auto",
  lineHeight: "normal",
  listStyleImage: "none",
  listStylePosition: "outside",
  listStyleType: "disc",
  marginBottom: "0px",
  marginLeft: "0px",
  marginRight: "0px",
  marginTop: "0px",
  maxHeight: "none",
  maxWidth: "none",
  minHeight: "0px",
  minWidth: "0px",
  mixBlendMode: "normal",
  objectFit: "fill",
  opacity: "1",
  order: "0",
  outlineColor: "rgb(0, 0, 0)",
  outlineOffset: "0px",
  outlineStyle: "none",
  outlineWidth: "0px",
  objectPosition: "50% 50%",
  overflow: "visible",
  overflowX: "visible",
  overflowY: "visible",
  position: "static",
  paddingBottom: "0px",
  paddingLeft: "0px",
  paddingRight: "0px",
  paddingTop: "0px",
  right: "auto",
  rowGap: "normal",
  strokeDasharray: "none",
  strokeDashoffset: "0px",
  strokeLinecap: "butt",
  strokeLinejoin: "miter",
  strokeMiterlimit: "4",
  strokeOpacity: "1",
  strokeWidth: "1px",
  textAlign: "start",
  textDecorationColor: "rgb(0, 0, 0)",
  textDecorationLine: "none",
  textDecorationStyle: "solid",
  textDecorationThickness: "auto",
  textIndent: "0px",
  textOverflow: "clip",
  textUnderlineOffset: "auto",
  textShadow: "none",
  textTransform: "none",
  top: "auto",
  transform: "none",
  transformOrigin: "auto",
  translate: "none",
  transitionProperty: "all",
  verticalAlign: "baseline",
  visibility: "visible",
  whiteSpace: "normal",
  width: "auto",
  willChange: "auto",
  writingMode: "horizontal-tb",
  zIndex: "auto",
  rotate: "none",
  scale: "none",
};
